### ISSUE TITLE
bot.guilds.array is not a function

### ISSUE THREAD

**Issue by NikiRakshu** [chalda/DiscordBot#156] opened 2020-07-12 15:04 UTC
at Client.<anonymous> (C:\Users\Nirma\Downloads\DiscordBot-master\discord_bot.js:276:62)
    at Client.emit (events.js:315:20)
    at WebSocketManager.triggerClientReady (C:\Users\Nirma\node_modules\discord.js\src\client\websocket\WebSocketManager.js:433:17)
    at WebSocketManager.checkShardsReady (C:\Users\Nirma\node_modules\discord.js\src\client\websocket\WebSocketManager.js:417:10)
    at WebSocketShard.<anonymous> (C:\Users\Nirma\node_modules\discord.js\src\client\websocket\WebSocketManager.js:199:14)
    at WebSocketShard.emit (events.js:315:20)
    at C:\Users\Nirma\node_modules\discord.js\src\client\websocket\WebSocketShard.js:479:12
    at Timeout._onTimeout (C:\Users\Nirma\node_modules\discord.js\src\client\BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by F9Alejandro** [comment] 2020-07-12 19:26
Please explain what was done to have this error occur. (was setup followed as described in the readme.md? was the files in question modified? are you using a different branch than main? etc)

**Comment by Einarin** [comment] 2020-07-13 18:06
This is caused by API changes in discord.js 12. Workaround until it gets fixed is to lock discord.js to version 11.

**Comment by Einarin** [comment] 2020-07-16 05:57
#157 fixes this. It's done except for the music player.

**Comment by Einarin** [comment] 2020-07-18 09:19
#157 is merged, resolving this. Update the bot if you're still seeing this issue.

**Closed by Einarin** 2020-07-18 09:19 UTC
